apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      run: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        run: rabbitmq
    spec:
      volumes:
      - name: readwrite-volume
        hostPath:
          path: /config
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
          - containerPort: 15672
            name: admin
          - containerPort: 5671
            name: ssl
          - containerPort: 5672
            name: msg
        volumeMounts:
        - mountPath: /etc/rabbitmq/conf.d
          name: readwrite-volume
